version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "sunday"
      commit-message:
          prefix: "Dep: "
      assignees:
          - "Xeffen25"
      labels:
          - "Dependencies"
      groups:
          npm-dependencies:
              patterns:
                  - "*"
